config/routes.rb
StoreApp::Application.routes.draw do

  get "sessions/new"
  root :to => 'products#index'
  get 'signup', to: 'admins#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :products
  resources :admins
  resources :sessions
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_secure_password

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_attached_file :photo, :styles => { :medium => "400x400>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def index
  	@admins = Admin.all 
  end

  def show
  	@admin = Admin.find(session[:admin_id])
  end

  def new 
  	@admin = Admin.new
  end

  def create
  	@admin = Admin.new(admin_params)
  	if @admin.save
  		session[:admin_id] = @admin.id 
  		redirect_to root_url, notice: "Admin created"
  	else
  		redirect_to signup_path
  	end
  end

  private
  def admin_params
  	params.require(:admin).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authorize, only: [:edit, :update]
  def index 
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

  def show
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		redirect_to root_url, notice: "Product added"
  	else
  		render "new"
  	end
  end

  private
  def product_params
  	params.require(:product).permit(:name, :description, :price, :photo, :admin_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by_username(params[:username])
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admins/_form.html.erb
<%= form_for @admin do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit(:class => 'btn btn-success') %>
 <% end %>

app/views/admins/index.html.erb
<h1>Admin page</h1>

app/views/admins/new.html.erb
<h1>Create a new Employee</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoreApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
		<% if current_user %>
		  <% if current_user.owner? %>
            <%= link_to "New Admin", new_admin_path %> |
		    
		 <% end %>
		<%= link_to "Home", root_url %> |
		<%= link_to "New Product", new_product_path %> |
		<%= link_to "Log Out", logout_path %> |
		 Logged in as <%= current_user.username %>
		<% else %>
		<%= link_to "Home", root_url %> |
		<%= link_to "Log in", login_path %>
		<% end %>



<%= bootstrap_flash %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :description %>
  <%= f.text_area :description %><br>
  <%= f.label :price %>
  <%= f.text_field :price %><br>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.submit(:class => 'btn btn-success') %>
 <% end %>

app/views/products/index.html.erb
<h1>Products</h1>

<% @products.each do |product| %>
	 <p><%= link_to product.name, product_path(product) %></p>
	<% end %>

app/views/products/new.html.erb
<h1> Add a new product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<H2><%= @product.name %></h2>
	<h3><%= @product.description %></h3>
	<h4>$<%= @product.price %></h4>

	<%= image_tag @product.photo(:thumb) %>
	